# Generated by Django 4.1 on 2022-09-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253)),
                ('ip_v4', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('ip_v6', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('mac_address', models.CharField(blank=True, default=None, max_length=17, null=True)),
                ('mac_vendor', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('notes', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('os', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hardware', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='DOWN', max_length=4)),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='date found')),
                ('last_seen', models.DateTimeField(auto_now_add=True, verbose_name='date seen')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.address')),
            ],
        ),
    ]
