# Generated by Django 4.1 on 2022-09-04 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, default=None, max_length=253, null=True)),
                ('ip_v4', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('ip_v6', models.GenericIPAddressField(blank=True, default=None, null=True)),
                ('mac_address', models.CharField(blank=True, default=None, max_length=17, null=True)),
                ('mac_vendor', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('type', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], default='TCP', max_length=3)),
                ('notes', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=253)),
                ('notes', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('status', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='DOWN', max_length=4)),
                ('os', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('hardware', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('first_seen', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='first_seen')),
                ('last_seen', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='last_seen')),
                ('address', models.ManyToManyField(to='entity.address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='resource',
            field=models.ManyToManyField(to='entity.resource'),
        ),
    ]
